### ISSUE TITLE
Sign In Bugs

### ISSUE THREAD

**Issue by AlxWang9966** [AlAuB/GiftMe#29]
* Sign in - **FAILED** 
  * ERROR message:
```
 Process: com.example.giftme, PID: 19840
    java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
        at com.example.giftme.Helpers.DataBaseHelper.convertMapIntoItem(DataBaseHelper.java:277)
        at com.example.giftme.Helpers.DataBaseHelper$1$1.lambda$onComplete$0$com-example-giftme-Helpers-DataBaseHelper$1$1(DataBaseHelper.java:342)
        at com.example.giftme.Helpers.DataBaseHelper$1$1$$ExternalSyntheticLambda0.accept(Unknown Source:6)
        at java.util.HashMap.forEach(HashMap.java:1292)
        at com.example.giftme.Helpers.DataBaseHelper$1$1.onComplete(DataBaseHelper.java:340)
```

**Comment by lchen456** [comment]
Fixed
