### ISSUE TITLE
Wishlist load collection needs to add new in order to update

### ISSUE THREAD

**Issue by AlxWang9966** [AlAuB/GiftMe#30]
* Wishlist Collection Load Item - - **FAILED** 
  * It is in the Firestore database, but not pulled to local

**Comment by AlxWang9966** [comment]
```
java.lang.NullPointerException: Attempt to invoke interface method 'void com.example.giftme.Fragments.SettingFragment$SignStatusListener.updateData(boolean)' on a null object reference
        at com.example.giftme.Fragments.SettingFragment$2$1.onCallback(SettingFragment.java:313)
        at com.example.giftme.Helpers.DataBaseHelper.lambda$checkUserExists$2(DataBaseHelper.java:174)
        at com.example.giftme.Helpers.DataBaseHelper$$ExternalSyntheticLambda12.onComplete(Unknown Source:2)
        at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7945)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by AlAuB** [comment]
Fixed
